name: "Create tasks"
on:
  push:
    branches:
      - feat-gajira
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create jira issue
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: DS
        issuetype: Task
        summary: |
          Test task for ${{ github.repository }}
        description: |
          Task description
        # fields: '{"Code Review URL": "github"}'
          fields: '{"customfield_11760": false}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"    
